# Generated by Django 5.1.2 on 2024-11-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pice_sifra', models.CharField(max_length=10)),
                ('pice_naziv', models.CharField(max_length=30)),
                ('pice_opis', models.CharField(max_length=100)),
                ('pice_kolicina_u_ml', models.FloatField()),
                ('pice_sadrzi_alkohol', models.BooleanField(default=False)),
                ('pice_vegansko', models.BooleanField(default=False)),
                ('pice_poj_cijena', models.FloatField()),
            ],
        ),
    ]
