# Generated by Django 5.1.1 on 2024-11-28 05:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konobar_korisnicko_ime', models.CharField(max_length=30, unique=True)),
                ('konobar_zaporka', models.CharField(max_length=128)),
                ('konobar_ime', models.CharField(max_length=50)),
                ('konobar_prezime', models.CharField(max_length=50)),
                ('konobar_datum_zaposlenja', models.DateField(auto_now_add=True)),
                ('konobar_zarada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('konobar_email', models.EmailField(max_length=254, unique=True)),
                ('konobar_telefon', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pice',
            name='pice_poj_cijena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narudzba_sifra', models.CharField(max_length=10)),
                ('narudzba_kolicina_stavki', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('narudzba_datum_kreiranja', models.DateTimeField(default=django.utils.timezone.now)),
                ('narudzba_placena', models.BooleanField(default=False)),
                ('narudzba_konobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narudzbe', to='main.konobar')),
            ],
        ),
        migrations.CreateModel(
            name='StavkaNarudzbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stavka_kolicina_pica', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stavka_ukupna_cijena', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('stavka_narudzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='main.narudzba')),
                ('stavka_pice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke_u_narudzbama', to='main.pice')),
            ],
        ),
    ]
