# Generated by Django 5.1.1 on 2024-12-15 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_konobar_alter_pice_pice_poj_cijena_narudzba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='narudzba_sifra',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pice',
            name='pice_sifra',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
