# Generated by Django 5.1.1 on 2024-12-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_narudzba_narudzba_kolicina_stavki'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzba',
            name='narudzba_ukupna_cijena',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
