# Generated by Django 5.1.1 on 2024-12-16 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_narudzba_narudzba_ukupna_cijena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stavkanarudzbe',
            name='id',
        ),
        migrations.AddField(
            model_name='stavkanarudzbe',
            name='stavka_sifra',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
